---
title: "NOMePlot - A Webtool for the analysis of NOMe data"
subtitle: "NOMe report"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    theme: lumen
---
### 1. Nucleosome occupancy and DNA methylation of cell population.
```{r, echo= FALSE, , fig.align = "center", fig.height=4, fig.width=9}
nucleoplot_plot5()

```
```{r, echo= FALSE, , fig.align = "center",  fig.height=4, fig.width=7}
nucleoplot_plot4()

```

### Information
#### - Values used in these graphics are provided in the attached information.csv files.
#### - You can download every graphic as a .png file with right-click and "Save image as..."

### 2. Nucleosome occupancy of individual cells (Line Chart).

```{r, echo= FALSE, , fig.align = "center",  fig.height=6, fig.width=10, comment = NA, message=FALSE}
plot_window_graphic()

```

### 3. Nucleosome occupancy of individual cells (Heatmap).

```{r, echo= FALSE, , fig.align = "center",  fig.height=6, fig.width=10, comment = NA, message=FALSE}
heatmap_window_graphic()

```
